import {PROJECT_CATEGORY, STATUS} from "./enum";

const itemData : Array<Projects> = [
  {
    img: require('../data/images/projects/my-library.gif'),
    title: 'MyLibrary',
    desc: 'Indexing Books to allow searching',
    demo: '',
    type: 'pdf',
    git: 'https://github.com/alexandre-em/CVIndexing',
    status: STATUS.DONE,
    category: PROJECT_CATEGORY.SOFTWARE_ENGINEERING,
  },
  {
    img: require('../data/images/projects/cv-indexer.png'),
    title: 'CV indexer',
    desc: 'Indexing CV to allow searching by keyword',
    demo: '',
    type: 'markdown',
    git: 'https://github.com/alexandre-em/CVIndexing',
    status: STATUS.DONE,
    category: PROJECT_CATEGORY.SOFTWARE_ENGINEERING,
  },
  {
    img: require('../data/images/projects/tuner.png'),
    title: 'Em Tuner',
    desc: 'Em Tuner is a guitar tuner',
    demo: 'https://alexandre-em.github.io/Em-tuner/',
    type: 'link',
    git: 'https://github.com/alexandre-em/Em-tuner',
    status: STATUS.DONE,
    category: PROJECT_CATEGORY.SOFTWARE_ENGINEERING,
  },
  {
    img: require('../data/images/projects/cloud2.png'),
    title: 'VM deploying service',
    desc: 'Microsoft Virtual Machine deploying service',
    demo: '',
    type: 'pdf',
    status: STATUS.DONE,
    category: PROJECT_CATEGORY.NETWORK_ENGINEERING,
  },
  {
    img: require('../data/images/projects/fortigate.png'),
    title: 'Certicating an application',
    desc: 'A CA certificating an app protected with Fortigate',
    demo: '',
    type: 'pdf',
    status: STATUS.DONE,
    category: PROJECT_CATEGORY.NETWORK_ENGINEERING,
  },
  {
    img: require('../data/images/projects/minesweeper.png'),
    title: 'Minesweeper',
    desc: 'Minesweeper clone coded with Elm',
    demo: 'https://minesweeper-elm.netlify.app/',
    type: 'link',
    git: 'https://github.com/alexandre-em/minesweeper',
    status: STATUS.DONE,
    category: PROJECT_CATEGORY.SOFTWARE_ENGINEERING,
  },
  {
    title: 'Nandarou',
    img: require('../data/images/projects/kanjiapp.png'),
    desc: 'A mobile app to learn Kanji',
    demo: 'https://expo.io/@alexandre-em/projects/nandarou',
    type: 'link',
    git: 'https://github.com/alexandre-em/nandarou',
    status: STATUS.DONE,
    category: PROJECT_CATEGORY.SOFTWARE_ENGINEERING,
  },
  {
    title: 'Birdy',
    img: require('../data/images/projects/birdy.jpg'),
    desc: 'A twitter clone',
    demo: '',
    type: 'markdown',
    git: 'https://github.com/alexandre-em/birdy',
    status: STATUS.DONE,
    category: PROJECT_CATEGORY.SOFTWARE_ENGINEERING,
  },
  {
    img: require('../data/images/projects/exml.png'),
    title: 'Exml',
    desc: 'Excel clone coded with Ocaml',
    demo: '',
    type: 'pdf',
    git: 'https://github.com/alexandre-em/exml',
    status: STATUS.DONE,
    category: PROJECT_CATEGORY.SOFTWARE_ENGINEERING,
  },
];

export default itemData;

